### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by Cxbrq** [fabbe50/LangSplit#3]
Hey I'd like to request an update for 1.19.1+ 
I saw there's one for 1.19.3 but as of now the mod pack I use can only work up to 1.19.2

**Comment by fabbe50** [comment]
If you're using 1.19.2, that's the latest Minecraft version that the mod is made for. I have yet to update to 1.19.3.
Not sure if the 1.19.2 version works with 1.19.1. Please test and confirm this if you can. Thanks!

**Comment by Madis0** [comment]
v2.1.4-beta already seems to run on 1.19.3 for me, only bug I noticed is that the multi-line option hides Mod Menu button.

**Comment by fabbe50** [comment]
There is a chance that (on fabric) the mod may cover multiple versions. 

As far as the mod menu bug goes, I am aware and I am working on it.

**Comment by Cxbrq** [comment]
I cant seem to find the download for this mod anymore, would you mind providing a direct link for version 1.19.2

**Comment by fabbe50** [comment]
Latest forge:
https://modrinth.com/mod/langsplit/version/2.1.3-beta
https://www.curseforge.com/minecraft/mc-mods/langsplit/files/4393847

Latest fabric:
https://www.curseforge.com/minecraft/mc-mods/langsplit/files/4406275
https://modrinth.com/mod/langsplit/version/2.1.4-beta

**Comment by Cxbrq** [comment]
looks like I need Cloth Config 8 except there are correctly no releases for 1.19.2

**Comment by Cxbrq** [comment]
Thank you I've installed the mod and both dependencies but I see it's still having trouble loading with create mod, dependencies seem to load fine though.
question... is this error fixable on your end or is this an issue that needs to be looked at by the create dev?

**Comment by fabbe50** [comment]
The fix I implemented for solving the create mod incompatibility, broke a lot of other things with Forge. So currently the fix is only available for Fabric. The error is technically on both ends, but I would rather account for this kind of issue on my end for better compatibility with other mods too.

**Comment by Cxbrq** [comment]
I see...  I was just curious and wanted to see if this mod would require much more work for other devs and their mods to work together.  Thanks for clearing that up for me.  Cant wait to get my hands on this mod and show it off to my friends who are learning english / korean

**Comment by fabbe50** [comment]
The bug with it crashing together with Create is now fixed for both Fabric and Forge. Should hopefully help with stability with a lot of other mods. As of the modmenu issue, it apparently applies to the create button as well. So #5 is being updated to cover this problem. Note that this only seems to apply to separate line mode. Closing this now.
