### ISSUE TITLE
Hotkey to swap

### ISSUE THREAD

**Issue by Madis0** [fabbe50/LangSplit#6]
As good as the idea is, displaying two strings at the same time does use a lot of screen space and creates clutter. 

How about a "flashcard method" - defining a hotkey that will show the strings in the defined language only while the button is held. (Or optionally - instead of held, toggled.)

**Comment by fabbe50** [comment]
The flashcard method is a lovely idea. It has now been added to the latest version of the mod. 
The config option is Display Mode and allows either Single Line, Dual Line, Flashcard Mode or Toggle Mode.
