### ISSUE TITLE
Arabic Translation is unreadable

### ISSUE THREAD

**Issue by WarmIceCream** [fabbe50/LangSplit#9]
Not sure if there could be anyway to fix it, or if Arabic might just be straight up incompatible, but installing this mod for the purpose of trying to learn some Arabic doesn't seem very helpful as it currently is.

**Comment by fabbe50** [comment]
Hi,

Could you please let me know the mod version, Minecraft version as well as if it's the Forge or Fabric version of the mod?

Thanks!

**Comment by WarmIceCream** [comment]
Sure, it was v2.3 on MC 1.20.1, and I think with Fabric API 0.85.0

**Comment by fabbe50** [comment]
Thank you!
May I ask how it's unreadable? 
Is it because of the font, size or something else?
Is it readable when Arabic is the only language selected?

I have to ask since I don't really know what it's supposed to look like.

**Comment by WarmIceCream** [comment]
The font just becomes very compressed and due to Arabic's detail in the shape of its letters, it makes it very hard to read, with a lot of letters looking too much like other letters, and some being unrecognisable.

Basically, the main issue seems to be the font is just too compressed

**Comment by fabbe50** [comment]
Great information, thank you!

I'll see if I can make it a little easier to read. :)

**Comment by WarmIceCream** [comment]
Thank you, if it helps, it seems to be worse with its vertical compression rather than horizontal

**Comment by fabbe50** [comment]
Let me know if this is better? Or does it need adjustments?

![image](https://github.com/fabbe50/LangSplit/assets/8047187/59d6fdc2-d149-4281-838a-857693a7a4fe)

**Comment by WarmIceCream** [comment]
It looks a lot more readable! I understand there's probably a limit for how the text will fit, but if it can be slightly larger that would be perfect

Even if not, thank you for taking the time to look into this, it's already looking so much better :)

**Comment by fabbe50** [comment]
I worked on fixing some other langauges that had similar issues as well as added a flashcard/toggle mode, that always shows the selected language in full and shows translation when a selected key is held/toggled.

I uploaded a version with these changes as well as some other neat features. 
I'm closing this issue with this. Sorry for taking so long getting this available.
